/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: commands.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "commands.pb-c.h"
void   hydroponics__command_reboot__init
                     (Hydroponics__CommandReboot         *message)
{
  static const Hydroponics__CommandReboot init_value = HYDROPONICS__COMMAND_REBOOT__INIT;
  *message = init_value;
}
size_t hydroponics__command_reboot__get_packed_size
                     (const Hydroponics__CommandReboot *message)
{
  assert(message->base.descriptor == &hydroponics__command_reboot__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hydroponics__command_reboot__pack
                     (const Hydroponics__CommandReboot *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hydroponics__command_reboot__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hydroponics__command_reboot__pack_to_buffer
                     (const Hydroponics__CommandReboot *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hydroponics__command_reboot__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hydroponics__CommandReboot *
       hydroponics__command_reboot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hydroponics__CommandReboot *)
     protobuf_c_message_unpack (&hydroponics__command_reboot__descriptor,
                                allocator, len, data);
}
void   hydroponics__command_reboot__free_unpacked
                     (Hydroponics__CommandReboot *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hydroponics__command_reboot__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hydroponics__command_set__init
                     (Hydroponics__CommandSet         *message)
{
  static const Hydroponics__CommandSet init_value = HYDROPONICS__COMMAND_SET__INIT;
  *message = init_value;
}
size_t hydroponics__command_set__get_packed_size
                     (const Hydroponics__CommandSet *message)
{
  assert(message->base.descriptor == &hydroponics__command_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hydroponics__command_set__pack
                     (const Hydroponics__CommandSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hydroponics__command_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hydroponics__command_set__pack_to_buffer
                     (const Hydroponics__CommandSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hydroponics__command_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hydroponics__CommandSet *
       hydroponics__command_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hydroponics__CommandSet *)
     protobuf_c_message_unpack (&hydroponics__command_set__descriptor,
                                allocator, len, data);
}
void   hydroponics__command_set__free_unpacked
                     (Hydroponics__CommandSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hydroponics__command_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hydroponics__command_impulse__init
                     (Hydroponics__CommandImpulse         *message)
{
  static const Hydroponics__CommandImpulse init_value = HYDROPONICS__COMMAND_IMPULSE__INIT;
  *message = init_value;
}
size_t hydroponics__command_impulse__get_packed_size
                     (const Hydroponics__CommandImpulse *message)
{
  assert(message->base.descriptor == &hydroponics__command_impulse__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hydroponics__command_impulse__pack
                     (const Hydroponics__CommandImpulse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hydroponics__command_impulse__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hydroponics__command_impulse__pack_to_buffer
                     (const Hydroponics__CommandImpulse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hydroponics__command_impulse__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hydroponics__CommandImpulse *
       hydroponics__command_impulse__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hydroponics__CommandImpulse *)
     protobuf_c_message_unpack (&hydroponics__command_impulse__descriptor,
                                allocator, len, data);
}
void   hydroponics__command_impulse__free_unpacked
                     (Hydroponics__CommandImpulse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hydroponics__command_impulse__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hydroponics__command__init
                     (Hydroponics__Command         *message)
{
  static const Hydroponics__Command init_value = HYDROPONICS__COMMAND__INIT;
  *message = init_value;
}
size_t hydroponics__command__get_packed_size
                     (const Hydroponics__Command *message)
{
  assert(message->base.descriptor == &hydroponics__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hydroponics__command__pack
                     (const Hydroponics__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hydroponics__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hydroponics__command__pack_to_buffer
                     (const Hydroponics__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hydroponics__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hydroponics__Command *
       hydroponics__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hydroponics__Command *)
     protobuf_c_message_unpack (&hydroponics__command__descriptor,
                                allocator, len, data);
}
void   hydroponics__command__free_unpacked
                     (Hydroponics__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hydroponics__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hydroponics__commands__init
                     (Hydroponics__Commands         *message)
{
  static const Hydroponics__Commands init_value = HYDROPONICS__COMMANDS__INIT;
  *message = init_value;
}
size_t hydroponics__commands__get_packed_size
                     (const Hydroponics__Commands *message)
{
  assert(message->base.descriptor == &hydroponics__commands__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hydroponics__commands__pack
                     (const Hydroponics__Commands *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hydroponics__commands__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hydroponics__commands__pack_to_buffer
                     (const Hydroponics__Commands *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hydroponics__commands__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Hydroponics__Commands *
       hydroponics__commands__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Hydroponics__Commands *)
     protobuf_c_message_unpack (&hydroponics__commands__descriptor,
                                allocator, len, data);
}
void   hydroponics__commands__free_unpacked
                     (Hydroponics__Commands *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &hydroponics__commands__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define hydroponics__command_reboot__field_descriptors NULL
#define hydroponics__command_reboot__field_indices_by_name NULL
#define hydroponics__command_reboot__number_ranges NULL
const ProtobufCMessageDescriptor hydroponics__command_reboot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hydroponics.CommandReboot",
  "CommandReboot",
  "Hydroponics__CommandReboot",
  "hydroponics",
  sizeof(Hydroponics__CommandReboot),
  0,
  hydroponics__command_reboot__field_descriptors,
  hydroponics__command_reboot__field_indices_by_name,
  0,  hydroponics__command_reboot__number_ranges,
  (ProtobufCMessageInit) hydroponics__command_reboot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hydroponics__command_set__field_descriptors[2] =
{
  {
    "output",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Hydroponics__CommandSet, n_output),
    offsetof(Hydroponics__CommandSet, output),
    &hydroponics__output__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Hydroponics__CommandSet, state),
    &hydroponics__output_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hydroponics__command_set__field_indices_by_name[] = {
  0,   /* field[0] = output */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange hydroponics__command_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hydroponics__command_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hydroponics.CommandSet",
  "CommandSet",
  "Hydroponics__CommandSet",
  "hydroponics",
  sizeof(Hydroponics__CommandSet),
  2,
  hydroponics__command_set__field_descriptors,
  hydroponics__command_set__field_indices_by_name,
  1,  hydroponics__command_set__number_ranges,
  (ProtobufCMessageInit) hydroponics__command_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hydroponics__command_impulse__field_descriptors[3] =
{
  {
    "output",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Hydroponics__CommandImpulse, n_output),
    offsetof(Hydroponics__CommandImpulse, output),
    &hydroponics__output__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Hydroponics__CommandImpulse, state),
    &hydroponics__output_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "delay_ms",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Hydroponics__CommandImpulse, delay_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hydroponics__command_impulse__field_indices_by_name[] = {
  2,   /* field[2] = delay_ms */
  0,   /* field[0] = output */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange hydroponics__command_impulse__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hydroponics__command_impulse__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hydroponics.CommandImpulse",
  "CommandImpulse",
  "Hydroponics__CommandImpulse",
  "hydroponics",
  sizeof(Hydroponics__CommandImpulse),
  3,
  hydroponics__command_impulse__field_descriptors,
  hydroponics__command_impulse__field_indices_by_name,
  1,  hydroponics__command_impulse__number_ranges,
  (ProtobufCMessageInit) hydroponics__command_impulse__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hydroponics__command__field_descriptors[3] =
{
  {
    "reboot",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hydroponics__Command, command_case),
    offsetof(Hydroponics__Command, reboot),
    &hydroponics__command_reboot__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hydroponics__Command, command_case),
    offsetof(Hydroponics__Command, set),
    &hydroponics__command_set__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "impulse",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hydroponics__Command, command_case),
    offsetof(Hydroponics__Command, impulse),
    &hydroponics__command_impulse__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hydroponics__command__field_indices_by_name[] = {
  2,   /* field[2] = impulse */
  0,   /* field[0] = reboot */
  1,   /* field[1] = set */
};
static const ProtobufCIntRange hydroponics__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor hydroponics__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hydroponics.Command",
  "Command",
  "Hydroponics__Command",
  "hydroponics",
  sizeof(Hydroponics__Command),
  3,
  hydroponics__command__field_descriptors,
  hydroponics__command__field_indices_by_name,
  1,  hydroponics__command__number_ranges,
  (ProtobufCMessageInit) hydroponics__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hydroponics__commands__field_descriptors[1] =
{
  {
    "command",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Hydroponics__Commands, n_command),
    offsetof(Hydroponics__Commands, command),
    &hydroponics__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hydroponics__commands__field_indices_by_name[] = {
  0,   /* field[0] = command */
};
static const ProtobufCIntRange hydroponics__commands__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor hydroponics__commands__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "hydroponics.Commands",
  "Commands",
  "Hydroponics__Commands",
  "hydroponics",
  sizeof(Hydroponics__Commands),
  1,
  hydroponics__commands__field_descriptors,
  hydroponics__commands__field_indices_by_name,
  1,  hydroponics__commands__number_ranges,
  (ProtobufCMessageInit) hydroponics__commands__init,
  NULL,NULL,NULL    /* reserved[123] */
};
