# proto-file: components/protos/config.proto
# proto-message: hydroponics.Config
sampling {
  humidity: 1000
  temperature: 1000
  ec_probe: 1500
  ec_probe_temp: 1000
  ph_probe: 1500
}
controller: {
  eca: {
    target: 1500
    min: 1400
    max: 1600
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
  pha: {
    target: 5.5
    min: 5.35
    max: 6.00
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
  ecb: {
    target: 1600
    min: 1500
    max: 1700
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
}
task: {
  name: "FooBar0"
  output: EXT_GPIO_B_0
  cron: {
    action: ON,
    # On at xx:00, every 2 seconds.
    expression: "0/30 * * * * *"
  }
  cron: {
    action: OFF,
    # On at xx:01, every 2 seconds.
    expression: "30/30 * * * * *"
  }
}
task: {
  name: "FooBar1"
  output: EXT_GPIO_A_7
  cron: {
    action: ON,
    # On every two minutes at xx:15.
    expression: "15 */2 * * * *"
  }
  cron: {
    action: OFF,
    # Off every two minutes at xx:45.
    expression: "45 */2 * * * *"
  }
}
