# proto-file: main/config/config.proto
# proto-message: hydroponics.Config
sampling {
  humidity: 1000
  temperature: 1000
  ec_probe: 1500
  ec_probe_temp: 1000
  ph_probe: 1500
}
controller: {
  ec: {
    target: 2000
    min: 1900
    max: 2100
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
  ph: {
    target: 6.2
    min: 6.1
    max: 6.35
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
}
task: {
  name: "FooBar0"
  output: EXT_GPIO_A_7
  cron: {
    action: ON,
    # On at xx:00, every 2 seconds.
    expression: "0/2 * * * * *"
  }
  cron: {
    action: OFF,
    # On at xx:01, every 2 seconds.
    expression: "1/2 * * * * *"
  }
}
task: {
  name: "FooBar1"
  output: EXT_GPIO_B_0
  output: EXT_GPIO_B_1
  cron: {
    action: ON,
    # On every two minutes at xx:15.
    expression: "15 */2 * * * *"
  }
  cron: {
    action: OFF,
    # Off every two minutes at xx:45.
    expression: "45 */2 * * * *"
  }
}
