# proto-file: components/protos/config.proto
# proto-message: hydroponics.Config
sampling {
  humidity: 1000
  temperature: 1000
  ec_probe: 1500
  ec_probe_temp: 1000
  ph_probe: 1500
}
controller: {
  eca: {
    target: 1500
    min: 1400
    max: 1600
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
  pha: {
    target: 5.5
    min: 5.35
    max: 6.00
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
  ecb: {
    target: 1600
    min: 1500
    max: 1700
    pid: {
      sampling: 20
      p: 1.0
      i: 0.0
      d: 0.0
    }
  }
}
hardware_id {
  name: "NA"
  dev_id: "37517103d8f15be34e2c"
  dps_id: 1,
  output: EXT_TUYA_OUT_1
}
hardware_id {
  name: "Strawberries"
  dev_id: "37517103d8f15be34e2c"
  dps_id: 2,
  output: EXT_TUYA_OUT_2
}
hardware_id {
  name: "Lettuce"
  dev_id: "37517103d8f15be34e2c"
  dps_id: 3,
  output: EXT_TUYA_OUT_3
}
task: {
  name: "FooBar0"
  output: EXT_GPIO_B_0
  cron: {
    state: OFF,
    # Off at xx:00.
    expression: "0 * * * * *"
  }
  cron: {
    state: ON,
    # On at xx:58.
    expression: "55 * * * * *"
  }
}
task: {
  name: "FooBar1"
  output: EXT_GPIO_A_7
  cron: {
    state: ON,
    # On every two minutes at xx:15.
    expression: "15 */2 * * * *"
  }
  cron: {
    state: OFF,
    # Off every two minutes at xx:45.
    expression: "45 */2 * * * *"
  }
}
startup_state {
  state: OFF
  output: EXT_GPIO_A_0
  output: EXT_GPIO_A_1
  output: EXT_GPIO_A_2
  output: EXT_GPIO_A_3
  output: EXT_GPIO_A_4
  output: EXT_GPIO_A_5
  output: EXT_GPIO_A_6
  output: EXT_GPIO_A_7
  output: EXT_GPIO_B_0
  output: EXT_GPIO_B_1
  output: EXT_GPIO_B_2
  output: EXT_GPIO_B_3
  output: EXT_GPIO_B_4
  output: EXT_GPIO_B_5
  output: EXT_GPIO_B_6
  output: EXT_GPIO_B_7
}
startup_state {
  state: ON
  output: EXT_TUYA_OUT_1
  output: EXT_TUYA_OUT_2
  output: EXT_TUYA_OUT_3
}
firmware {
  type: RELEASE
  arch: ESP32
  version: "0.1"
}